/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Spark',
      items: [
        'spark/installation',
        'spark/quick-start',
        'spark/deployment',
        {
          type: 'category',
          label: 'Configuration',
          items: [
            // TODO we can use generated-index to create some leading page like https://docusaurus.io/docs/category/guides
            {
              type: 'autogenerated',
              dirName: 'spark/configuration',
            },
          ],
        },
        {
          type: 'category',
          label: 'Commands',
          items: [
            {
              type: 'autogenerated',
              dirName: 'spark/commands',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Flink',
      items: [
        'flink/installation',
        'flink/quick-start',
        'flink/deployment',
        {
          type: 'category',
          label: 'Configuration',
          items: [
            {
              type: 'autogenerated',
              dirName: 'flink/configuration',
            },
          ],
        },
        {
          type: 'category',
          label: 'Commands',
          items: [
            {
              type: 'autogenerated',
              dirName: 'flink/commands',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'developement',
      items: [
        'developement/setup',
        'developement/NewLicenseGuide',
      ],
    },
    'FAQ',
  ]
};

module.exports = sidebars
